import { Artifact, defaultLimits, PanelData, Report, Run, Snapshot } from '../common/model';
import { Collection, Store, Versioned } from '../server/store';

export const snapshot: Snapshot = { key: 'requests', title: 'Requests by day', type: 'line', refs: [{ type: 'visualization', id: 'visual-1' }, { type: 'index-pattern', id: 'logs' }], importRef: { type: 'visualization', id: 'visual-1' }, indexPattern: { id: 'logs', attributes: { title: 'logs-*', timeFieldName: '@timestamp', fields: JSON.stringify([{ name: '@timestamp', type: 'date' }, { name: 'bytes', type: 'number' }]) } }, vis: { type: 'line', params: { addLegend: true }, aggs: [{ id: '1', enabled: true, type: 'count', schema: 'metric', params: {} }, { id: '2', enabled: true, type: 'date_histogram', schema: 'segment', params: { field: '@timestamp', interval: '1d' } }] }, queries: [], filters: [] };
export const report: Report = { id: 'report-1', revision: 1, schemaVersion: 1, owner: 'alice', tenant: 'operations', organizationScope: 'operations', updatedAt: '2026-09-21T12:00:00Z', title: 'Operations weekly report', timezone: 'America/New_York', timeRange: { from: 'now-7d/d', to: 'now/d' }, query: { language: 'kuery', query: '' }, filters: [], sources: [snapshot], branding: { organization: 'NORTHSTAR TECHNOLOGIES', header: 'Operations intelligence', footer: 'Prepared for the operations team', color: '#2457a7', alignment: 'left', showPeriod: true, showGenerated: true, showPageNumbers: true }, sections: [{ id: 'intro', kind: 'text', text: 'Weekly performance overview', style: 'heading', bold: true, alignment: 'left' }, { id: 'chart', kind: 'panels', columns: 1, sources: ['requests'] }] };
export const run: Run = { id: 'fixture-run', report, owner: report.owner, tenant: report.tenant, trigger: 'preview', scheduledAt: '2026-09-21T12:00:00Z', createdAt: '2026-09-21T12:00:00Z', expiresAt: '2026-10-21T12:00:00Z', from: '2026-09-14T04:00:00Z', to: '2026-09-21T03:59:59Z', status: 'running', attempt: 1, fence: 1 };
export const panels: PanelData[] = [{ key: 'requests', title: 'Requests by day', type: 'line', columns: ['Day', 'Requests'], bucketCount: 1, schemas: ['segment', 'metric'], params: { addLegend: true }, rows: [12, 16, 14, 25, 22, 29, 31].map((n, i) => [{ text: `Sep ${14 + i}`, value: `2026-09-${14 + i}` }, { text: `${n},000`, value: n * 1000 }]) }];
export function demoFixture() {
  const sample = structuredClone(run), data = structuredClone(panels);
  sample.report.sections.splice(1, 0, { id: 'intro-body', kind: 'text', text: 'Service demand increased throughout the reporting period. The charts and tables below use the same frozen reporting interval. All values in this example are synthetic demonstration data.', style: 'body', bold: false, alignment: 'left' });
  data.unshift({ key: 'total', title: 'Weekly requests', type: 'metric', columns: ['Requests'], bucketCount: 0, schemas: ['metric'], params: {}, rows: [[{ text: '149,000', value: 149000 }]] });
  sample.report.sections.splice(2, 0, { id: 'metric', kind: 'panels', columns: 1, sources: ['total'] });
  sample.report.sections.push({ id: 'break', kind: 'pageBreak' }, { id: 'table', kind: 'panels', columns: 1, sources: ['table'] });
  data.push({ key: 'table', title: 'Service detail', type: 'table', columns: ['Service', 'Requests', 'Success rate'], bucketCount: 1, schemas: ['bucket', 'metric', 'metric'], params: {}, rows: Array.from({ length: 55 }, (_, i) => [{ text: `Service ${String(i + 1).padStart(2, '0')}`, value: `service-${i}` }, { text: (1200 + i * 37).toLocaleString('en-US'), value: 1200 + i * 37 }, { text: '99.95%', value: .9995 }]) });
  return { run: sample, panels: data, limits: defaultLimits };
}
export class MemoryStore implements Store {
  data = new Map<string, Versioned<any>>();
  async init() {}
  async get<T>(collection: Collection, id: string) { const v = this.data.get(`${collection}:${id}`); return v ? structuredClone(v) as Versioned<T> : undefined; }
  async create<T>(collection: Collection, id: string, value: T) { const key = `${collection}:${id}`; if (this.data.has(key)) return false; this.data.set(key, { value: structuredClone(value), seq: 0, term: 1 }); return true; }
  async replace<T>(collection: Collection, id: string, value: T, old: Versioned<unknown>) { const key = `${collection}:${id}`, current = this.data.get(key); if (!current || current.seq !== old.seq || current.term !== old.term) return false; this.data.set(key, { value: structuredClone(value), seq: old.seq + 1, term: old.term }); return true; }
  async remove(collection: Collection, id: string, old: Versioned<unknown>) { const current = this.data.get(`${collection}:${id}`); if (!current || current.seq !== old.seq) return false; return this.data.delete(`${collection}:${id}`); }
  async list<T>(collection: Collection, filters: Record<string, unknown> = {}, limit = 1000) { return [...this.data.entries()].filter(([key, version]) => key.startsWith(`${collection}:`) && Object.entries(filters).every(([field, value]) => Array.isArray(value) ? value.includes(version.value[field]) : version.value[field] === value)).slice(0, limit).map(([, version]) => structuredClone(version)) as Versioned<T>[]; }
  async cleanup(now: string) { for (const [key, record] of this.data) if ((key.startsWith('artifacts:') || key.startsWith('runs:')) && Date.parse(record.value.expiresAt) < Date.parse(now)) this.data.delete(key); }
}
