import React, { useEffect, useState } from 'react';
import { EuiButton, EuiButtonEmpty, EuiCallOut } from '@elastic/eui';
import { ReportInput, Report, Schedule, Snapshot } from '../common/model';
import { PdfPreview } from './pdf_preview';

const uid = () => crypto.randomUUID();
const blank = (): ReportInput => ({ title: 'Untitled report', timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC', timeRange: { from: 'now-7d/d', to: 'now/d' }, query: { language: 'kuery', query: '' }, filters: [], branding: { organization: '', header: '', footer: '', color: '#2457a7', alignment: 'left', showPeriod: true, showGenerated: true, showPageNumbers: true }, sources: [], sections: [{ id: uid(), kind: 'text', text: '', style: 'body', bold: false, alignment: 'left' }] });
const asInput = (report: Report): ReportInput => { const { id, revision, owner, tenant, schemaVersion, updatedAt, grant, ...input } = report; return input; };
export function App({ core }: { core: any }) {
  const [tab, setTab] = useState('Reports'), [editor, setEditor] = useState(false);
  const [draft, setDraft] = useState<ReportInput>(blank), [saved, setSaved] = useState<Report>();
  const [reports, setReports] = useState<any[]>([]), [schedules, setSchedules] = useState<Schedule[]>([]), [runs, setRuns] = useState<any[]>([]);
  const [error, setError] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false);
  const [pdf, setPdf] = useState<Uint8Array>(), [previewRevision, setPreviewRevision] = useState(''), [previewRun, setPreviewRun] = useState<string>();
  const [search, setSearch] = useState(''), [found, setFound] = useState<any[]>([]), [imported, setImported] = useState<any[]>([]), [selected, setSelected] = useState<Set<number>>(new Set());
  const [filterText, setFilterText] = useState('[]');
  const [sourcePage, setSourcePage] = useState(1), [sourceTotal, setSourceTotal] = useState(0);
  const discover = async (page: number) => { const result = await api(`/sources?search=${encodeURIComponent(search)}&page=${page}`); setFound(result.sources); setSourcePage(page); setSourceTotal(result.total); };
  const [schedule, setSchedule] = useState<any>(), [nextDates, setNextDates] = useState<string[]>([]), [preset, setPreset] = useState('cron');
  const [grants, setGrants] = useState<any[]>([]);
  const [health, setHealth] = useState<any>(), [adminSchedules, setAdminSchedules] = useState<any[]>([]);
  const api = (path: string, method = 'GET', body?: any) => {
    const [pathname, query] = path.split('?');
    return core.http.fetch(`/api/better_reports${pathname}`, { method, query: Object.fromEntries(new URLSearchParams(query)), ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
  };
  const action = async (fn: () => Promise<void>) => { setBusy(true); setError(''); setNotice(''); try { await fn(); } catch (e: any) { setError(e.body?.message ?? e.message ?? 'The request failed.'); } finally { setBusy(false); } };
  const load = async () => { const [a, b, c] = await Promise.all([api('/reports'), api('/schedules'), api('/runs')]); setReports(a); setSchedules(b); setRuns(c); };
  const showPdf = async (id: string) => { const result = await api(`/runs/${encodeURIComponent(id)}/pdf?encoding=base64`); const binary = atob(result.pdf); setPdf(Uint8Array.from(binary, char => char.charCodeAt(0))); };
  useEffect(() => { void action(async () => {
    await load();
    const params = new URLSearchParams(window.location.search), sourceId = params.get('sourceId'), sourceType = params.get('sourceType');
    if (sourceId && ['dashboard', 'visualization'].includes(sourceType ?? '')) { setEditor(true); setImported(await api('/sources/import', 'POST', { id: sourceId, type: sourceType })); }
  }); }, []);
  useEffect(() => {
    if (!previewRun) return;
    let stopped = false;
    const timer = setInterval(() => { void (async () => {
      try { const run = await api(`/runs/${previewRun}`); if (stopped) return;
        if (run.status === 'complete') { clearInterval(timer); await showPdf(previewRun); setPreviewRun(undefined); setNotice('Your PDF is ready.'); }
        if (['failed', 'cancelled', 'delivery_unknown'].includes(run.status)) { clearInterval(timer); setPreviewRun(undefined); setError(run.error?.message ?? `Report ${run.status}`); }
      } catch (e: any) { if (!stopped) { clearInterval(timer); setPreviewRun(undefined); setError(e.body?.message ?? e.message); } }
    })(); }, 1500);
    return () => { stopped = true; clearInterval(timer); };
  }, [previewRun]);
  const update = (patch: Partial<ReportInput>) => setDraft(previous => ({ ...previous, ...patch }));
  const newReport = () => { setDraft(blank()); setSaved(undefined); setPdf(undefined); setPreviewRevision(''); setImported([]); setFilterText('[]'); setEditor(true); };
  const editReport = async (id: string) => { const report = await api(`/reports/${encodeURIComponent(id)}`); setSaved(report); setDraft(asInput(report)); setFilterText(JSON.stringify(report.filters, null, 2)); setEditor(true); setPdf(undefined); };
  const currentInput = () => ({ ...draft, filters: JSON.parse(filterText) });
  const fingerprint = JSON.stringify(draft) + '\n' + filterText;
  const dirty = !saved || JSON.stringify(draft) !== JSON.stringify(asInput(saved)) || filterText !== JSON.stringify(saved.filters, null, 2);
  const saveReport = async () => { const input = currentInput(); const report = saved ? await api(`/reports/${saved.id}`, 'PUT', { revision: saved.revision, report: input }) : await api('/reports', 'POST', input); setSaved(report); setDraft(asInput(report)); setFilterText(JSON.stringify(report.filters, null, 2)); setNotice('Report saved.'); await load(); };
  const move = (index: number, delta: number) => { const sections = [...draft.sections]; [sections[index], sections[index + delta]] = [sections[index + delta], sections[index]]; update({ sections }); };
  const addSelected = () => {
    const sources: Snapshot[] = imported.filter((_, i) => selected.has(i)).map(item => ({ ...item.source, key: uid() }));
    update({ sources: [...draft.sources, ...sources], sections: [...draft.sections, ...sources.map(source => ({ id: uid(), kind: 'panels' as const, columns: 1 as const, sources: [source.key] }))] });
    setImported([]); setSelected(new Set());
  };
  const removeSection = (id: string) => {
    const sections = draft.sections.filter(section => section.id !== id);
    const used = new Set(sections.flatMap(section => section.kind === 'panels' ? section.sources : []));
    update({ sections, sources: draft.sources.filter(source => used.has(source.key)) });
  };
  const changeSection = (id: string, patch: any) => update({ sections: draft.sections.map(section => section.id === id ? { ...section, ...patch } : section) });
  const editSchedule = (existing?: Schedule) => { setNextDates([]); setPreset('cron'); setSchedule(existing ? { ...existing, recipientText: existing.recipients.join(', ') } : { reportId: reports[0]?.id ?? '', cron: '0 8 * * 1', timezone: draft.timezone, enabled: true, recipientText: '', subject: 'Your scheduled report', message: 'Please find your report attached.' }); };
  const scheduleInput = () => ({ reportId: schedule.reportId, cron: schedule.cron, timezone: schedule.timezone, enabled: schedule.enabled, recipients: schedule.recipientText.split(/[,;\n]/).map((v: string) => v.trim()).filter(Boolean), subject: schedule.subject, message: schedule.message });
  return <main className="br-app">
    <header className="br-header"><div className="br-logo">B<span>R</span></div><div><h1>BetterReports</h1><p>Dashboards to documents.</p></div><div className="br-header-right"><span className="br-tag">OpenSearch 3.8.0</span><EuiButton onClick={() => { setTab('Reports'); newReport(); }}>Create report</EuiButton></div></header>
    <nav className="br-tabs" aria-label="BetterReports navigation">{['Reports', 'Schedules', 'Run history', 'Authorizations', 'Administration'].map(label => <button key={label} aria-current={tab === label ? 'page' : undefined} className={tab === label ? 'active' : ''} onClick={() => { setTab(label); void action(async () => { await load(); if (label === 'Authorizations') setGrants((await api('/grants')).grants); if (label === 'Administration') { setHealth(await api('/health')); setAdminSchedules(await api('/admin/schedules')); } }); }}>{label}</button>)}</nav>
    {error && <div className="br-message"><EuiCallOut title="Something needs attention" color="danger"><p>{error}</p></EuiCallOut></div>}
    {notice && <div role="status" className="br-notice">{notice}</div>}
    {tab === 'Reports' && !editor && <section className="br-content"><div className="br-section-heading"><div><h2>Your reports</h2><p>Reusable reports with fresh data and your branding.</p></div><button disabled={busy} onClick={() => void action(load)}>Refresh</button></div>{reports.length ? <div className="br-cards">{reports.map(report => <article className="br-report-card" key={report.id}><span className="br-eyebrow">PDF REPORT · LETTER</span><h3>{report.title}</h3><p>Revision {report.revision} · Updated {new Date(report.updatedAt).toLocaleDateString()}</p><div className="br-actions"><EuiButton onClick={() => void action(() => editReport(report.id))}>Open report</EuiButton><button onClick={() => void action(async () => { const result = await api(`/reports/${report.id}/runs`, 'POST', {}); setNotice(`Report queued: ${result.runId}`); })}>Generate</button><button onClick={() => void action(async () => { if (window.confirm(`Delete ${report.title}? Its schedules will be disabled.`)) { await api(`/reports/${report.id}`, 'DELETE'); await load(); } })}>Delete</button></div></article>)}</div> : <div className="br-empty"><h2>Make your first report.</h2><p>Start with an existing dashboard or saved visualization.</p><EuiButton fill onClick={newReport}>Create report</EuiButton></div>}</section>}
    {tab === 'Reports' && editor && <><div className="br-editor-toolbar"><EuiButtonEmpty onClick={() => setEditor(false)}>All reports</EuiButtonEmpty><span>{saved ? `Revision ${saved.revision}` : 'Unsaved report'}</span><div className="br-actions"><button disabled={busy || !saved || dirty} title="Save report changes before refreshing sources" onClick={() => void action(async () => { const report = await api(`/reports/${saved!.id}/refresh`, 'POST', { revision: saved!.revision }); setSaved(report); setDraft(asInput(report)); setNotice('Saved source configurations refreshed.'); })}>Refresh sources</button><EuiButton disabled={busy} onClick={() => void action(saveReport)}>Save report</EuiButton><button disabled={busy || !saved || dirty} onClick={() => void action(async () => { const report = await api(`/reports/${saved!.id}/authorize`, "POST", { revision: saved!.revision }); setSaved(report); setNotice("Scheduled reporting authorized until explicitly revoked. SAML group changes do not revoke this grant."); })}>Authorize scheduling</button><EuiButton fill disabled={busy || !!previewRun} onClick={() => void action(async () => { const input = currentInput(); const result = await api('/preview', 'POST', input); setPreviewRevision(fingerprint); setPreviewRun(result.runId); setNotice('Generating your PDF…'); })}>{previewRun ? 'Generating…' : 'Generate preview'}</EuiButton>{previewRun && <button onClick={() => void action(async () => { await api(`/runs/${previewRun}/cancel`, 'POST', {}); setPreviewRun(undefined); })}>Cancel</button>}</div></div>
    <div className="br-workspace"><div className="br-builder">
      <section className="br-box"><h2>Report settings</h2><label>Report title<input value={draft.title} onChange={e => update({ title: e.target.value })} /></label><div className="br-form-grid"><label>From<input value={draft.timeRange.from} onChange={e => update({ timeRange: { ...draft.timeRange, from: e.target.value } })} /></label><label>To<input value={draft.timeRange.to} onChange={e => update({ timeRange: { ...draft.timeRange, to: e.target.value } })} /></label></div><label>Timezone<input value={draft.timezone} onChange={e => update({ timezone: e.target.value })} /></label><p className="br-help">Use ISO dates or date math, for example now-7d/d. The report interval applies to every panel.</p><details><summary>Additional query and filters</summary><label>Query language<select value={draft.query.language} onChange={e => update({ query: { ...draft.query, language: e.target.value as any } })}><option value="kuery">DQL</option><option value="lucene">Lucene</option></select></label><label>Query<input value={draft.query.query} onChange={e => update({ query: { ...draft.query, query: e.target.value } })} /></label><label>Additional filters (OpenSearch Dashboards JSON)<textarea rows={4} value={filterText} onChange={e => setFilterText(e.target.value)} /></label></details></section>
      <section className="br-box"><h2>Add dashboard content</h2><div className="br-inline"><input aria-label="Search dashboards and visualizations" placeholder="Search saved dashboards or visualizations" value={search} onChange={e => setSearch(e.target.value)} /><button disabled={busy} onClick={() => void action(() => discover(1))}>Search</button></div>{found.map(item => <div className="br-source" key={`${item.type}:${item.id}`}><span><strong>{item.title}</strong><small>{item.type}</small></span><button onClick={() => void action(async () => { setImported(await api('/sources/import', 'POST', { type: item.type, id: item.id })); setSelected(new Set()); })}>Select panels</button></div>)}
      {sourceTotal > 50 && <div className="br-pagination"><button disabled={busy || sourcePage === 1} onClick={() => void action(() => discover(sourcePage - 1))}>Previous sources</button><span>Page {sourcePage} of {Math.ceil(sourceTotal / 50)}</span><button disabled={busy || sourcePage * 50 >= sourceTotal} onClick={() => void action(() => discover(sourcePage + 1))}>Next sources</button></div>}
      {imported.length > 0 && <div className="br-import"><p>Choose the panels to include. Unsupported panels cannot be added.</p>{imported.map((item, i) => <label className="br-check" key={i}><input type="checkbox" disabled={!item.source} checked={selected.has(i)} onChange={e => { const next = new Set(selected); if (e.target.checked) next.add(i); else next.delete(i); setSelected(next); }} /><span>{item.title}{item.error && <small className="br-error-text">{item.error.message}</small>}</span></label>)}<button disabled={!selected.size} onClick={addSelected}>Add {selected.size || ''} selected panels</button><button onClick={() => setImported([])}>Dismiss</button></div>}</section>
      <section className="br-box"><div className="br-section-heading"><h2>Report sections</h2><span>{draft.sections.length} sections</span></div>{draft.sections.map((section, index) => <article className="br-section" key={section.id}><div className="br-section-controls"><strong>{index + 1}. {section.kind === 'panels' ? 'Dashboard content' : section.kind === 'text' ? 'Text' : 'Page break'}</strong><button title="Move up" aria-label="Move section up" disabled={index === 0} onClick={() => move(index, -1)}>↑</button><button title="Move down" aria-label="Move section down" disabled={index === draft.sections.length - 1} onClick={() => move(index, 1)}>↓</button><button aria-label="Remove section" onClick={() => removeSection(section.id)}>Remove</button></div>
        {section.kind === 'text' && <><div className="br-form-grid"><label>Style<select value={section.style} onChange={e => changeSection(section.id, { style: e.target.value })}><option value="body">Body</option><option value="heading">Heading</option></select></label><label>Alignment<select value={section.alignment} onChange={e => changeSection(section.id, { alignment: e.target.value })}>{['left', 'center', 'right'].map(value => <option key={value}>{value}</option>)}</select></label></div><label className="br-check"><input type="checkbox" checked={section.bold} onChange={e => changeSection(section.id, { bold: e.target.checked })} />Bold</label><textarea aria-label="Section text" rows={3} value={section.text} onChange={e => changeSection(section.id, { text: e.target.value })} /></>}
        {section.kind === 'panels' && <><p>{section.sources.map(key => draft.sources.find(s => s.key === key)?.title).join(' + ')}</p><label>Layout<select value={section.columns} onChange={e => changeSection(section.id, { columns: Number(e.target.value), sources: Number(e.target.value) === 1 ? section.sources.slice(0, 1) : section.sources })}><option value={1}>Full width</option><option value={2}>Two columns</option></select></label>{section.columns === 2 && <label>Second panel<select value={section.sources[1] ?? ''} onChange={e => changeSection(section.id, { sources: e.target.value ? [section.sources[0], e.target.value] : [section.sources[0]] })}><option value="">Empty column</option>{draft.sources.filter(s => s.type !== 'table' && s.key !== section.sources[0]).map(source => <option key={source.key} value={source.key}>{source.title}</option>)}</select></label>}</>}
      </article>)}<div className="br-actions"><button onClick={() => update({ sections: [...draft.sections, { id: uid(), kind: 'text', text: '', style: 'body', bold: false, alignment: 'left' }] })}>Add text</button><button onClick={() => update({ sections: [...draft.sections, { id: uid(), kind: 'pageBreak' }] })}>Add page break</button></div></section>
      <section className="br-box"><h2>Branding</h2><p className="br-help">The header and footer repeat on every page.</p>{(['organization', 'header', 'footer'] as const).map(key => <label key={key}>{key === 'organization' ? 'Organization' : `${key[0].toUpperCase()}${key.slice(1)} text`}<input value={draft.branding[key]} maxLength={key === 'organization' ? 120 : 180} onChange={e => update({ branding: { ...draft.branding, [key]: e.target.value } })} /></label>)}<div className="br-form-grid"><label>Accent color<input type="color" value={draft.branding.color} onChange={e => update({ branding: { ...draft.branding, color: e.target.value } })} /></label><label>Alignment<select value={draft.branding.alignment} onChange={e => update({ branding: { ...draft.branding, alignment: e.target.value as any } })}>{['left', 'center', 'right'].map(value => <option key={value}>{value}</option>)}</select></label></div><label>Logo (PNG or JPEG, up to 1 MB)<input type="file" accept="image/png,image/jpeg" onChange={e => { const file = e.target.files?.[0]; if (!file) return; if (file.size > 1024 * 1024) { setError('Choose a logo smaller than 1 MB.'); return; } const reader = new FileReader(); reader.onload = () => update({ branding: { ...draft.branding, logo: String(reader.result) } }); reader.readAsDataURL(file); }} /></label>{draft.branding.logo && <div className="br-inline"><img className="br-brand-logo" src={draft.branding.logo} alt="Report logo" /><button onClick={() => update({ branding: { ...draft.branding, logo: undefined } })}>Remove logo</button></div>}{(['showPeriod', 'showGenerated', 'showPageNumbers'] as const).map((key, i) => <label className="br-check" key={key}><input type="checkbox" checked={draft.branding[key]} onChange={e => update({ branding: { ...draft.branding, [key]: e.target.checked } })} />{['Reporting period', 'Generation date', 'Page X of Y'][i]}</label>)}</section>
    </div><PdfPreview bytes={pdf} workerUrl={core.http.basePath.prepend('/api/better_reports/pdf.worker.min.mjs')} filename={draft.title} stale={!!pdf && fingerprint !== previewRevision} /></div></>}
    {tab === 'Schedules' && <section className="br-content"><div className="br-section-heading"><div><h2>Scheduled delivery</h2><p>Send fresh PDF reports, even when your browser is closed. Open and authorize the saved report before enabling a schedule. Authorization lasts until revoked.</p></div><EuiButton disabled={!reports.length} onClick={() => editSchedule()}>Create schedule</EuiButton></div>
      {schedule && <section className="br-box br-schedule-editor"><h3>{schedule.id ? 'Edit schedule' : 'New schedule'}</h3><div className="br-form-grid"><label>Report<select value={schedule.reportId} onChange={e => setSchedule({ ...schedule, reportId: e.target.value })}>{reports.map(r => <option key={r.id} value={r.id}>{r.title}</option>)}</select></label><label>Timezone<input value={schedule.timezone} onChange={e => setSchedule({ ...schedule, timezone: e.target.value })} /></label></div><div className="br-form-grid"><label>Recurrence<select value={preset} onChange={e => { setPreset(e.target.value); setSchedule({ ...schedule, cron: ({ daily: '0 8 * * *', weekly: '0 8 * * 1', monthly: '0 8 1 * *' } as any)[e.target.value] ?? schedule.cron }); }}><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="cron">Custom cron</option></select></label><label>Schedule (minute hour day month weekday)<input value={schedule.cron} onChange={e => setSchedule({ ...schedule, cron: e.target.value })} /></label></div><button onClick={() => void action(async () => setNextDates(await api('/schedules/next', 'POST', { cron: schedule.cron, timezone: schedule.timezone })))}>Preview next five runs</button>{nextDates.length > 0 && <ul>{nextDates.map(date => <li key={date}>{new Date(date).toLocaleString(undefined, { timeZone: schedule.timezone })} · {schedule.timezone}</li>)}</ul>}<label>Recipients (comma separated)<textarea rows={2} value={schedule.recipientText} onChange={e => setSchedule({ ...schedule, recipientText: e.target.value })} /></label><label>Subject<input value={schedule.subject} onChange={e => setSchedule({ ...schedule, subject: e.target.value })} /></label><label>Message<textarea rows={3} value={schedule.message} onChange={e => setSchedule({ ...schedule, message: e.target.value })} /></label><label className="br-check"><input type="checkbox" checked={schedule.enabled} onChange={e => setSchedule({ ...schedule, enabled: e.target.checked })} />Enabled</label><div className="br-actions"><EuiButton fill disabled={busy} onClick={() => void action(async () => { const input = scheduleInput(); if (schedule.id) await api(`/schedules/${schedule.id}`, 'PUT', { revision: schedule.revision, schedule: input }); else await api('/schedules', 'POST', input); setSchedule(undefined); await load(); setNotice('Schedule saved.'); })}>Save schedule</EuiButton><button onClick={() => setSchedule(undefined)}>Cancel</button></div></section>}
      <div className="br-table-wrap"><table><thead><tr><th>Report</th><th>Schedule</th><th>Next run</th><th>Status</th><th>Actions</th></tr></thead><tbody>{schedules.map(item => <tr key={item.id}><td>{reports.find(r => r.id === item.reportId)?.title ?? item.reportId}</td><td>{item.cron}<small>{item.timezone}</small></td><td>{new Date(item.nextAt).toLocaleString()}<small>{item.skipped} missed occurrences skipped</small></td><td>{item.enabled ? 'Active' : 'Paused'}</td><td><div className="br-actions"><button onClick={() => editSchedule(item)}>Edit</button><button onClick={() => void action(async () => { const { id, owner, tenant, revision, nextAt, lastLocal, skipped, updatedAt, ...input } = item; await api(`/schedules/${id}`, 'PUT', { revision, schedule: { ...input, enabled: !item.enabled } }); await load(); })}>{item.enabled ? 'Pause' : 'Resume'}</button><button onClick={() => void action(async () => { await api(`/schedules/${item.id}/run`, 'POST', {}); setNotice('Test delivery queued for the configured recipients.'); })}>Send now / test</button><button onClick={() => void action(async () => { if (window.confirm('Delete this schedule?')) { await api(`/schedules/${item.id}`, 'DELETE'); await load(); } })}>Delete</button></div></td></tr>)}</tbody></table>{!schedules.length && <p className="br-empty">No schedules yet. Save a report to set up email delivery.</p>}</div></section>}
    {tab === 'Run history' && <section className="br-content"><div className="br-section-heading"><div><h2>Run history</h2><p>Generation progress, downloads, and email delivery results.</p></div><button onClick={() => void action(load)}>Refresh</button></div><div className="br-table-wrap"><table><thead><tr><th>Report</th><th>Started</th><th>Status</th><th>Details</th><th>Actions</th></tr></thead><tbody>{runs.map(run => <tr key={run.id}><td>{run.title}<small>Revision {run.revision} · {run.trigger}</small></td><td>{new Date(run.createdAt).toLocaleString()}</td><td><span className={`br-status br-status-${run.status}`}>{run.status.replace('_', ' ')}</span></td><td>{run.error?.message ?? `Attempt ${run.attempt}`}</td><td><div className="br-actions">{run.artifactId && <button onClick={() => void action(async () => { await showPdf(run.id); setPreviewRevision(''); setTab('Report preview'); })}>View PDF</button>}{['queued', 'running'].includes(run.status) && <button onClick={() => void action(async () => { await api(`/runs/${run.id}/cancel`, 'POST', {}); await load(); })}>Cancel</button>}</div></td></tr>)}</tbody></table>{!runs.length && <p className="br-empty">Generated reports will appear here.</p>}</div></section>}
    {tab === 'Report preview' && <section className="br-content"><button onClick={() => setTab('Run history')}>Back to history</button><PdfPreview bytes={pdf} workerUrl={core.http.basePath.prepend('/api/better_reports/pdf.worker.min.mjs')} filename="BetterReports" stale={false} /></section>}
    {tab === 'Authorizations' && <section className="br-content"><h2>Reporting authorizations</h2><p>Authorizations remain valid indefinitely until revoked. Signing out or removing SAML group membership does not revoke them. Saved report changes require new authorization.</p><button onClick={() => void action(async () => setGrants((await api('/grants')).grants))}>Refresh</button><table><thead><tr><th>Report</th><th>Owner / tenant</th><th>Lifetime</th><th>Action</th></tr></thead><tbody>{grants.map(grant => <tr key={grant.id}><td>{grant.title ?? reports.find(r => r.id === grant.reportId)?.title ?? grant.reportId}<small>Revision {grant.revision}</small></td><td>{grant.owner}<small>{grant.tenant || 'Global'}</small></td><td>{grant.revoked ? 'Revoked' : 'Until revoked'}</td><td><button disabled={busy || grant.revoked} onClick={() => void action(async () => { await api(`/grants/${grant.id}/revoke`, 'POST', {}); setGrants((await api('/grants')).grants); setNotice('Authorization revoked. Future query and delivery checks will fail.'); })}>Revoke authorization</button></td></tr>)}</tbody></table></section>}
    {tab === 'Administration' && <section className="br-content"><h2>Reporting health</h2>{health && <><div className="br-cards">{[['Queue', health.queueDepth], ['Active jobs', health.active], ['Completed on this instance', health.completed], ['Failed on this instance', health.failures]].map(([label, value]) => <div className="br-report-card" key={label}><span className="br-eyebrow">{label}</span><h2>{value}</h2></div>)}</div><p>Scheduler heartbeat: {health.heartbeat} · Last error: {health.lastError || 'None'}</p><h3>Manage schedules</h3><table><thead><tr><th>Owner</th><th>Tenant</th><th>Status</th><th>Action</th></tr></thead><tbody>{adminSchedules.map(item => <tr key={item.id}><td>{item.owner}</td><td>{item.tenant}</td><td>{item.enabled ? 'Active' : 'Paused'}</td><td><button disabled={!item.enabled} onClick={() => void action(async () => { await api(`/admin/schedules/${item.id}/pause`, 'POST', {}); setAdminSchedules(await api('/admin/schedules')); })}>Pause</button></td></tr>)}</tbody></table></>}</section>}
  </main>;
}
